// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALFIowMhRQCIObI_YAbsSav4n_bVTkHjk',
    appId: '1:275860591563:web:d30044790a01bb4cf65c4e',
    messagingSenderId: '275860591563',
    projectId: 'safespace-897b5',
    authDomain: 'safespace-897b5.firebaseapp.com',
    storageBucket: 'safespace-897b5.firebasestorage.app',
    measurementId: 'G-B613XY6HR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCktVZxMdSwk47-mP2KBoYHXEMXywyK0aU',
    appId: '1:275860591563:android:2388c9a0d017b85ff65c4e',
    messagingSenderId: '275860591563',
    projectId: 'safespace-897b5',
    storageBucket: 'safespace-897b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2fCPZc2ePiLFc68wOKZN-3kGHxr0eFiw',
    appId: '1:275860591563:ios:389b1046d7cbb380f65c4e',
    messagingSenderId: '275860591563',
    projectId: 'safespace-897b5',
    storageBucket: 'safespace-897b5.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2fCPZc2ePiLFc68wOKZN-3kGHxr0eFiw',
    appId: '1:275860591563:ios:389b1046d7cbb380f65c4e',
    messagingSenderId: '275860591563',
    projectId: 'safespace-897b5',
    storageBucket: 'safespace-897b5.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALFIowMhRQCIObI_YAbsSav4n_bVTkHjk',
    appId: '1:275860591563:web:7115e7c6a24988dcf65c4e',
    messagingSenderId: '275860591563',
    projectId: 'safespace-897b5',
    authDomain: 'safespace-897b5.firebaseapp.com',
    storageBucket: 'safespace-897b5.firebasestorage.app',
    measurementId: 'G-6ZEJ560FFJ',
  );
}
